### ISSUE TITLE
video upload problem

### ISSUE THREAD

**Issue by jakamoo33** [ramtinak/InstaPost#1]
System.ComponentModel.Win32Exception
  HResult=0x80004005
  İleti=Sistem belirtilen dosyayı bulamıyor
  Kaynak=System
  StackTrace:
   konum System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   konum System.Diagnostics.Process.Start()
   konum FFmpegFa.FFmpeg.ExtractImageFromVideo(String inputFile, String outputFile)
   konum InstaPost.Views.PostView.<UploadButtonClick>d__2.MoveNext() C:\Users\cs\Desktop\InstaPost-master\InstaPost\Views\PostView.xaml.cs içinde: 66. satır

**Comment by jakamoo33** [comment]
why close?

**Comment by ramtinak** [comment]
This app is not supported anymore
